# Generated by Django 3.2.9 on 2021-11-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name'], name='company_emp_last_na_300dd8_idx'),
        ),
    ]
